export const SET_PROJECT = 'SET_PROJECT'
export const REMOVE_PROJECT = 'REMOVE_PROJECT'

export const ADD_FILTER = 'ADD_FILTER'
export const REMOVE_FILTER = 'REMOVE_FILTER'
export const EMPTY_FILTERS = 'EMPTY_FILTERS'

export const GENERAL_ADD_PROJECT = 'GENERAL_ADD_PROJECT'
export const GENERAL_REMOVE_PROJECT = 'GENERAL_REMOVE_PROJECT'
export const GENERAL_EDIT_PROJECT = 'GENERAL_EDIT_PROJECT'
export const GENERAL_ARCHIVE_PROJECT = 'GENERAL_ARCHIVE_PROJECT'
